name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # Specifies the use of a specific, self-hosted runner

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: podman build -t my-nginx-image .

    # - name: Push Image to Registry
    #   run: |
    #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    #     docker push my-nginx-image
